# Lidar Range value 350°-10°
Range_0     Values_0
# Lidar Range value 80°-100°
Range_90    Values_90
# Lidar Range value 170°-190°
Range_180   Values_180
# Lidar Range value 260°-280°
Range_270   Values_270

# Lidar mean value of range 350°-10°
Mean_Range_0 Mean_Range_0
# Lidar mean value of range 80°-100°
Mean_Range_90 Mean_Range_90
# Lidar mean value of range 170°-190°
Mean_Range_180 Mean_Range_180
# Lidar mean value of range 260°-280°
Mean_Range_270 Mean_Range_270